const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Behaviors.Fade,
		C3.Behaviors.Bullet,
		C3.Behaviors.wrap,
		C3.Behaviors.destroy,
		C3.Behaviors.NoSave,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.OnLayoutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Keyboard.Cnds.OnKeyCode,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion
	];
};
self.C3_JsPropNameTable = [
	{backgroundprincipal: 0},
	{Solid: 0},
	{espinho: 0},
	{ScrollTo: 0},
	{Platform: 0},
	{BoundToLayout: 0},
	{Steve: 0},
	{BROKU: 0},
	{Dry: 0},
	{Keyboard: 0},
	{Audio: 0},
	{vida: 0},
	{txtVida: 0},
	{JogaDnv: 0},
	{Mouse: 0},
	{obsidian: 0},
	{morreu2: 0},
	{renascer: 0},
	{menuprincipal: 0},
	{ec9089b4018e920bd42879af3b: 0},
	{Sprite: 0},
	{pxDefault_Superflat_world: 0},
	{Sólido: 0},
	{Esmaecer: 0},
	{Sprite2: 0},
	{casa: 0},
	{MojangStudios: 0},
	{b26770b630653475d851a5256ab9c0f: 0},
	{bb6d38b9450ff7d56ffb8aca65dab: 0},
	{f14178538211f9290a41f2453f6c417c: 0},
	{cdb17e7dc997bf0cdd92c4e5ae0e8e: 0},
	{a: 0},
	{f5c4e8d735de35233d39fb9bf2b6d8fd: 0},
	{Sprite4: 0},
	{Jogar: 0},
	{Sprite5: 0},
	{Projétil: 0},
	{DarAVolta: 0},
	{Sprite6: 0},
	{ab5858703e41eb7177a688ed79fd: 0},
	{Sprite7: 0},
	{Plataforma: 0},
	{Sprite8: 0},
	{DestruirForaDoLayout: 0},
	{NãoSalvar: 0},
	{flechasteve: 0},
	{Sprite9: 0},
	{Sprite3: 0},
	{fa831249e62cba42d41b1a0413eb: 0},
	{fa831249e62cba42d41b1a0413eb2: 0},
	{d8cb68560b0f17fd8bbd45c60fabfe: 0},
	{Sprite10: 0},
	{Vida: 0}
];

self.InstanceType = {
	backgroundprincipal: class extends self.ITiledBackgroundInstance {},
	espinho: class extends self.ISpriteInstance {},
	Steve: class extends self.ISpriteInstance {},
	BROKU: class extends self.ISpriteInstance {},
	Dry: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	vida: class extends self.ISpriteInstance {},
	txtVida: class extends self.ITextInstance {},
	JogaDnv: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	obsidian: class extends self.ISpriteInstance {},
	morreu2: class extends self.ISpriteInstance {},
	renascer: class extends self.ISpriteInstance {},
	menuprincipal: class extends self.ISpriteInstance {},
	ec9089b4018e920bd42879af3b: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	pxDefault_Superflat_world: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	casa: class extends self.ISpriteInstance {},
	MojangStudios: class extends self.ISpriteInstance {},
	b26770b630653475d851a5256ab9c0f: class extends self.ISpriteInstance {},
	bb6d38b9450ff7d56ffb8aca65dab: class extends self.ISpriteInstance {},
	f14178538211f9290a41f2453f6c417c: class extends self.ISpriteInstance {},
	cdb17e7dc997bf0cdd92c4e5ae0e8e: class extends self.ISpriteInstance {},
	a: class extends self.ISpriteInstance {},
	f5c4e8d735de35233d39fb9bf2b6d8fd: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Jogar: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	ab5858703e41eb7177a688ed79fd: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	flechasteve: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	fa831249e62cba42d41b1a0413eb: class extends self.ISpriteInstance {},
	fa831249e62cba42d41b1a0413eb2: class extends self.ISpriteInstance {},
	d8cb68560b0f17fd8bbd45c60fabfe: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {}
}